//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Address.
        /// </summary>
        public static string primary_address {
            get {
                return ResourceManager.GetString("primary_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product internal code.
        /// </summary>
        public static string product_code {
            get {
                return ResourceManager.GetString("product_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product image.
        /// </summary>
        public static string product_image {
            get {
                return ResourceManager.GetString("product_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record doesn&apos;t exist in our system.
        /// </summary>
        public static string record_not_exist {
            get {
                return ResourceManager.GetString("record_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Address.
        /// </summary>
        public static string secondary_address {
            get {
                return ResourceManager.GetString("secondary_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship to this adddress.
        /// </summary>
        public static string ship_to_this_address {
            get {
                return ResourceManager.GetString("ship_to_this_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province/Region.
        /// </summary>
        public static string state_province_region {
            get {
                return ResourceManager.GetString("state_province_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        public static string unit_price {
            get {
                return ResourceManager.GetString("unit_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be {1} characters or less..
        /// </summary>
        public static string validation_max_field_lenght {
            get {
                return ResourceManager.GetString("validation_max_field_lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string validation_required_field {
            get {
                return ResourceManager.GetString("validation_required_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP / Postal Code.
        /// </summary>
        public static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
